app:
  name: vproapp
  image: vprofile/vprofileapp
  tag: latest
  port: 8080
  replicas: 1

database:
  name: vprodb
  image: vprofile/vprofiledb
  port: 3306
  replicas: 1

memcached:
  name: vpromc
  image: memcached
  port: 11211
  replicas: 1

rabbitmq:
  name: vpromq01
  image: rabbitmq
  port: 5672
  replicas: 1

secrets:
  dbPass: dnByb2RicGFzcw==
  rmqPass: Z3Vlc3Q=

service:
  name: my-app
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: alb
  host: vprofile.salimnextdev.site
  path: /