apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.name }}
  labels:
    app: {{ .Values.database.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.database.name }}
  replicas: {{ .Values.database.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.database.name }}
    spec:
      containers:
      - name: {{ .Values.database.name }}
        image: {{ .Values.database.image }}
        ports:
        - name: vprodb-port
          containerPort: {{ .Values.database.port }}
        env: 
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: app-secret
               key: db-pass