apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rabbitmq.name }}
  labels:
    app: {{ .Values.rabbitmq.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.rabbitmq.name }}
  replicas: {{ .Values.rabbitmq.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.rabbitmq.name }}
    spec:
      containers:
      - name: {{ .Values.rabbitmq.name }}
        image: {{ .Values.rabbitmq.image }}
        ports:
        - name: vpromq01-port
          containerPort: {{ .Values.rabbitmq.port }}
        env: 
         - name: RABBITMQ_DEFAULT_PASS
           valueFrom:
             secretKeyRef:
               name: app-secret
               key: rmq-pass
         - name: RABBITMQ_DEFAULT_USER
           value: "guest"